export const ADD_RESERVATION = 'ADD_RESERVATION';
export const REMOVE_RESERVATION = 'REMOVE_RESERVATION';
export const RECEIVE_RESERVATIONS = 'RECEIVE_RESERVATIONS';
export const RECEIVE_ROCKETS = 'RECEIVE_ROCKETS';
export const RECEIVE_ROCKET_RESERVE = 'RECEIVE_ROCKET_RESERVE';
export const RECEIVE_ROCKET_RESERVE_CANCELLATION = 'RECEIVE_ROCKET_RESERVE_CANCELLATION';
